/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.rdsl2.ui;

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Rdsl2UiModule /* implements AbstractRdsl2UiModule  */{
}
