/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.rdsl2.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
public class Rdsl2OutlineTreeProvider extends DefaultOutlineTreeProvider {
}
