/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.rdsl2.ide;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class Rdsl2IdeSetup /* implements Rdsl2StandaloneSetup  */{
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nRdsl2RuntimeModule cannot be resolved."
      + "\nType mismatch: cannot convert from Rdsl2IdeModule to Module");
  }
}
