/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.rdsl2.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Rdsl2IdeModule /* implements AbstractRdsl2IdeModule  */{
}
